export const USER_CONTENT_TEXT_MIN_LENGTH = 10;
export const USER_CONTENT_TEXT_MAX_LENGTH = 3500;

export const USER_NAME_MIN_LENGTH = 2;
export const USER_NAME_MAX_LENGTH = 50;

export const USER_PASSWORD_MIN_LENGTH = 8;
export const USER_PASSWORD_MAX_LENGTH = 200;

export const USER_EMAIL_MAX_LENGTH = 254;
