// Жанры и теги AniList.
// type='genre' → genre_in, type='tag' → tag_in в GraphQL запросе.

export interface Genre {
  value: string;
  label: string;
  type: 'genre' | 'tag';
}

// ─── Основные жанры AniList (genre_in) ────────────────────────────────────────

export const ANIME_GENRES: Genre[] = [
  { value: 'Action',        label: 'Экшн',             type: 'genre' },
  { value: 'Adventure',     label: 'Приключения',       type: 'genre' },
  { value: 'Comedy',        label: 'Комедия',           type: 'genre' },
  { value: 'Drama',         label: 'Драма',             type: 'genre' },
  { value: 'Fantasy',       label: 'Фэнтези',           type: 'genre' },
  { value: 'Romance',       label: 'Романтика',         type: 'genre' },
  { value: 'Sci-Fi',        label: 'Фантастика',        type: 'genre' },
  { value: 'Slice of Life', label: 'Повседневность',    type: 'genre' },
  { value: 'Supernatural',  label: 'Сверхъест.',        type: 'genre' },
  { value: 'Mystery',       label: 'Мистика',           type: 'genre' },
  { value: 'Psychological', label: 'Психология',        type: 'genre' },
  { value: 'Horror',        label: 'Ужасы',             type: 'genre' },
  { value: 'Thriller',      label: 'Триллер',           type: 'genre' },
  { value: 'Sports',        label: 'Спорт',             type: 'genre' },
  { value: 'Mecha',         label: 'Меха',              type: 'genre' },
  { value: 'Music',         label: 'Музыка',            type: 'genre' },
  { value: 'Mahou Shoujo',  label: 'Махо-сёдзё',        type: 'genre' },
  { value: 'Ecchi',         label: 'Этти',              type: 'genre' },

  // ─── Теги AniList (tag_in) ──────────────────────────────────────────────────

  { value: '4-koma',                       label: '4-кома',                         type: 'tag' },
  { value: 'Achromatic',                   label: 'Ахроматический',                 type: 'tag' },
  { value: 'Achronological Order',         label: 'Нехронологический порядок',      type: 'tag' },
  { value: 'Acrobatics',                   label: 'Акробатика',                     type: 'tag' },
  { value: 'Acting',                       label: 'Актёрство',                      type: 'tag' },
  { value: 'Adoption',                     label: 'Усыновление',                    type: 'tag' },
  { value: 'Advertisement',                label: 'Реклама',                        type: 'tag' },
  { value: 'Afterlife',                    label: 'Загробная жизнь',                type: 'tag' },
  { value: 'Age Gap',                      label: 'Разница в возрасте',             type: 'tag' },
  { value: 'Age Regression',               label: 'Омоложение',                     type: 'tag' },
  { value: 'Agender',                      label: 'Агендер',                        type: 'tag' },
  { value: 'Agriculture',                  label: 'Сельское хозяйство',             type: 'tag' },
  { value: 'Airsoft',                      label: 'Страйкбол',                      type: 'tag' },
  { value: 'Alchemy',                      label: 'Алхимия',                        type: 'tag' },
  { value: 'Aliens',                       label: 'Пришельцы',                      type: 'tag' },
  { value: 'Alternate Universe',           label: 'Альтернативная вселенная',       type: 'tag' },
  { value: 'American Football',            label: 'Американский футбол',            type: 'tag' },
  { value: 'Amnesia',                      label: 'Амнезия',                        type: 'tag' },
  { value: 'Anachronism',                  label: 'Анахронизм',                     type: 'tag' },
  { value: 'Ancient China',                label: 'Древний Китай',                  type: 'tag' },
  { value: 'Angels',                       label: 'Ангелы',                         type: 'tag' },
  { value: 'Animals',                      label: 'Животные',                       type: 'tag' },
  { value: 'Anthology',                    label: 'Антология',                      type: 'tag' },
  { value: 'Anthropomorphism',             label: 'Антропоморфизм',                 type: 'tag' },
  { value: 'Anti-Hero',                    label: 'Антигерой',                      type: 'tag' },
  { value: 'Archery',                      label: 'Стрельба из лука',               type: 'tag' },
  { value: 'Aromantic',                    label: 'Аромантик',                      type: 'tag' },
  { value: 'Arranged Marriage',            label: 'Брак по договорённости',         type: 'tag' },
  { value: 'Artificial Intelligence',      label: 'Искусственный интеллект',        type: 'tag' },
  { value: 'Asexual',                      label: 'Асексуал',                       type: 'tag' },
  { value: 'Assassins',                    label: 'Убийцы',                         type: 'tag' },
  { value: 'Astronomy',                    label: 'Астрономия',                     type: 'tag' },
  { value: 'Athletics',                    label: 'Лёгкая атлетика',               type: 'tag' },
  { value: 'Augmented Reality',            label: 'Дополненная реальность',         type: 'tag' },
  { value: 'Autobiographical',             label: 'Автобиографический',             type: 'tag' },
  { value: 'Aviation',                     label: 'Авиация',                        type: 'tag' },
  { value: 'Badminton',                    label: 'Бадминтон',                      type: 'tag' },
  { value: 'Ballet',                       label: 'Балет',                          type: 'tag' },
  { value: 'Band',                         label: 'Музыкальная группа',             type: 'tag' },
  { value: 'Bar',                          label: 'Бар',                            type: 'tag' },
  { value: 'Baseball',                     label: 'Бейсбол',                        type: 'tag' },
  { value: 'Basketball',                   label: 'Баскетбол',                      type: 'tag' },
  { value: 'Battle Royale',                label: 'Королевская битва',              type: 'tag' },
  { value: 'Biographical',                 label: 'Биографический',                 type: 'tag' },
  { value: 'Bisexual',                     label: 'Бисексуальность',               type: 'tag' },
  { value: 'Blackmail',                    label: 'Шантаж',                         type: 'tag' },
  { value: 'Board Game',                   label: 'Настольная игра',                type: 'tag' },
  { value: 'Boarding School',              label: 'Школа-интернат',                 type: 'tag' },
  { value: 'Body Horror',                  label: 'Боди-хоррор',                    type: 'tag' },
  { value: 'Body Image',                   label: 'Образ тела',                     type: 'tag' },
  { value: 'Body Swapping',                label: 'Смена тела',                     type: 'tag' },
  { value: 'Bowling',                      label: 'Боулинг',                        type: 'tag' },
  { value: 'Boxing',                       label: 'Бокс',                           type: 'tag' },
  { value: "Boys' Love",                   label: 'Яой',                            type: 'tag' },
  { value: 'Bullying',                     label: 'Буллинг',                        type: 'tag' },
  { value: 'Butler',                       label: 'Дворецкий',                      type: 'tag' },
  { value: 'Calligraphy',                  label: 'Каллиграфия',                    type: 'tag' },
  { value: 'Camping',                      label: 'Кемпинг',                        type: 'tag' },
  { value: 'Cannibalism',                  label: 'Каннибализм',                    type: 'tag' },
  { value: 'Card Battle',                  label: 'Карточные битвы',                type: 'tag' },
  { value: 'Cars',                         label: 'Автомобили',                     type: 'tag' },
  { value: 'Centaur',                      label: 'Кентавр',                        type: 'tag' },
  { value: 'CGI',                          label: 'ЦГИ',                            type: 'tag' },
  { value: 'Cheerleading',                 label: 'Черлидинг',                      type: 'tag' },
  { value: 'Chibi',                        label: 'Чиби',                           type: 'tag' },
  { value: 'Chimera',                      label: 'Химера',                         type: 'tag' },
  { value: 'Chuunibyou',                   label: 'Тюниб',                          type: 'tag' },
  { value: 'Circus',                       label: 'Цирк',                           type: 'tag' },
  { value: 'Class Struggle',               label: 'Классовая борьба',               type: 'tag' },
  { value: 'Classic Literature',           label: 'Классическая литература',        type: 'tag' },
  { value: 'Classical Music',              label: 'Классическая музыка',            type: 'tag' },
  { value: 'Clone',                        label: 'Клон',                           type: 'tag' },
  { value: 'Coastal',                      label: 'Побережье',                      type: 'tag' },
  { value: 'Cohabitation',                 label: 'Совместное проживание',          type: 'tag' },
  { value: 'College',                      label: 'Колледж',                        type: 'tag' },
  { value: 'Coming of Age',                label: 'Взросление',                     type: 'tag' },
  { value: 'Conspiracy',                   label: 'Заговор',                        type: 'tag' },
  { value: 'Cosmic Horror',                label: 'Космический хоррор',             type: 'tag' },
  { value: 'Cosplay',                      label: 'Косплей',                        type: 'tag' },
  { value: 'Cowboys',                      label: 'Ковбои',                         type: 'tag' },
  { value: 'Creature Taming',              label: 'Приручение существ',             type: 'tag' },
  { value: 'Crime',                        label: 'Преступность',                   type: 'tag' },
  { value: 'Criminal Organization',        label: 'Криминальная организация',       type: 'tag' },
  { value: 'Crossdressing',                label: 'Кроссдрессинг',                  type: 'tag' },
  { value: 'Crossover',                    label: 'Кроссовер',                      type: 'tag' },
  { value: 'Cult',                         label: 'Культ',                          type: 'tag' },
  { value: 'Cultivation',                  label: 'Культивация',                    type: 'tag' },
  { value: 'Curses',                       label: 'Проклятия',                      type: 'tag' },
  { value: 'Cute Boys Doing Cute Things',  label: 'Милые парни делают милые вещи', type: 'tag' },
  { value: 'Cute Girls Doing Cute Things', label: 'Милые девочки делают милые вещи', type: 'tag' },
  { value: 'Cyberpunk',                    label: 'Киберпанк',                      type: 'tag' },
  { value: 'Cyborg',                       label: 'Киборг',                         type: 'tag' },
  { value: 'Cycling',                      label: 'Велоспорт',                      type: 'tag' },
  { value: 'Dancing',                      label: 'Танцы',                          type: 'tag' },
  { value: 'Death Game',                   label: 'Смертельная игра',               type: 'tag' },
  { value: 'Delinquents',                  label: 'Хулиганы',                       type: 'tag' },
  { value: 'Demons',                       label: 'Демоны',                         type: 'tag' },
  { value: 'Denpa',                        label: 'Дэнпа',                          type: 'tag' },
  { value: 'Desert',                       label: 'Пустыня',                        type: 'tag' },
  { value: 'Detective',                    label: 'Детектив',                       type: 'tag' },
  { value: 'Dinosaurs',                    label: 'Динозавры',                      type: 'tag' },
  { value: 'Disability',                   label: 'Инвалидность',                   type: 'tag' },
  { value: 'Dissociative Identities',      label: 'Расщепление личности',           type: 'tag' },
  { value: 'Dragons',                      label: 'Драконы',                        type: 'tag' },
  { value: 'Drawing',                      label: 'Рисование',                      type: 'tag' },
  { value: 'Drugs',                        label: 'Наркотики',                      type: 'tag' },
  { value: 'Dullahan',                     label: 'Дуллахан',                       type: 'tag' },
  { value: 'Dungeon',                      label: 'Подземелье',                     type: 'tag' },
  { value: 'Dystopian',                    label: 'Антиутопия',                     type: 'tag' },
  { value: 'E-Sports',                     label: 'Киберспорт',                     type: 'tag' },
  { value: 'Eco-Horror',                   label: 'Экохоррор',                      type: 'tag' },
  { value: 'Economics',                    label: 'Экономика',                      type: 'tag' },
  { value: 'Educational',                  label: 'Образовательный',               type: 'tag' },
  { value: 'Elderly Protagonist',          label: 'Пожилой протагонист',            type: 'tag' },
  { value: 'Elf',                          label: 'Эльф',                           type: 'tag' },
  { value: 'Ensemble Cast',                label: 'Ансамблевый каст',               type: 'tag' },
  { value: 'Environmental',                label: 'Экология',                       type: 'tag' },
  { value: 'Episodic',                     label: 'Эпизодический',                  type: 'tag' },
  { value: 'Ero Guro',                     label: 'Эрогуро',                        type: 'tag' },
  { value: 'Espionage',                    label: 'Шпионаж',                        type: 'tag' },
  { value: 'Estranged Family',             label: 'Отчуждённая семья',              type: 'tag' },
  { value: 'Exorcism',                     label: 'Экзорцизм',                      type: 'tag' },
  { value: 'Fairy',                        label: 'Фея',                            type: 'tag' },
  { value: 'Fairy Tale',                   label: 'Сказка',                         type: 'tag' },
  { value: 'Fake Relationship',            label: 'Ненастоящие отношения',          type: 'tag' },
  { value: 'Family Life',                  label: 'Семейная жизнь',                 type: 'tag' },
  { value: 'Fashion',                      label: 'Мода',                           type: 'tag' },
  { value: 'Female Harem',                 label: 'Женский гарем',                  type: 'tag' },
  { value: 'Female Protagonist',           label: 'Девушка-протагонист',            type: 'tag' },
  { value: 'Femboy',                       label: 'Фэмбой',                         type: 'tag' },
  { value: 'Fencing',                      label: 'Фехтование',                     type: 'tag' },
  { value: 'Filmmaking',                   label: 'Кинопроизводство',               type: 'tag' },
  { value: 'Firefighters',                 label: 'Пожарные',                       type: 'tag' },
  { value: 'Fishing',                      label: 'Рыбалка',                        type: 'tag' },
  { value: 'Fitness',                      label: 'Фитнес',                         type: 'tag' },
  { value: 'Flash',                        label: 'Флэш-анимация',                  type: 'tag' },
  { value: 'Food',                         label: 'Кулинария',                      type: 'tag' },
  { value: 'Football',                     label: 'Футбол',                         type: 'tag' },
  { value: 'Foreign',                      label: 'Зарубежный',                     type: 'tag' },
  { value: 'Found Family',                 label: 'Обретённая семья',               type: 'tag' },
  { value: 'Fugitive',                     label: 'Беглец',                         type: 'tag' },
  { value: 'Full CGI',                     label: 'Полный ЦГИ',                     type: 'tag' },
  { value: 'Full Color',                   label: 'Полноцветный',                   type: 'tag' },
  { value: 'Gambling',                     label: 'Азартные игры',                  type: 'tag' },
  { value: 'Gangs',                        label: 'Банды',                          type: 'tag' },
  { value: 'Gender Bending',               label: 'Смена пола',                     type: 'tag' },
  { value: 'Ghost',                        label: 'Призраки',                       type: 'tag' },
  { value: 'Go',                           label: 'Го (игра)',                       type: 'tag' },
  { value: 'Goblin',                       label: 'Гоблины',                        type: 'tag' },
  { value: 'Gods',                         label: 'Боги',                           type: 'tag' },
  { value: 'Golf',                         label: 'Гольф',                          type: 'tag' },
  { value: 'Gore',                         label: 'Кровь и жестокость',             type: 'tag' },
  { value: 'Guns',                         label: 'Оружие',                         type: 'tag' },
  { value: 'Gyaru',                        label: 'Гяру',                           type: 'tag' },
  { value: 'Handball',                     label: 'Гандбол',                        type: 'tag' },
  { value: 'Henshin',                      label: 'Хэнсин',                         type: 'tag' },
  { value: 'Heterosexual',                 label: 'Гетеросексуальный',              type: 'tag' },
  { value: 'Hikikomori',                   label: 'Хикикомори',                     type: 'tag' },
  { value: 'Hip-hop Music',               label: 'Хип-хоп',                        type: 'tag' },
  { value: 'Historical',                   label: 'Историческое',                   type: 'tag' },
  { value: 'Homeless',                     label: 'Бездомность',                    type: 'tag' },
  { value: 'Horticulture',                 label: 'Садоводство',                    type: 'tag' },
  { value: 'Ice Skating',                  label: 'Фигурное катание',               type: 'tag' },
  { value: 'Idol',                         label: 'Айдолы',                         type: 'tag' },
  { value: 'Indigenous Cultures',          label: 'Коренные культуры',              type: 'tag' },
  { value: 'Inn',                          label: 'Гостиница',                      type: 'tag' },
  { value: 'Isekai',                       label: 'Исекай',                         type: 'tag' },
  { value: 'Iyashikei',                    label: 'Ияшикэй',                        type: 'tag' },
  { value: 'Jazz Music',                   label: 'Джаз',                           type: 'tag' },
  { value: 'Josei',                        label: 'Дзёсэй',                         type: 'tag' },
  { value: 'Judo',                         label: 'Дзюдо',                          type: 'tag' },
  { value: 'Kabuki',                       label: 'Кабуки',                         type: 'tag' },
  { value: 'Kaiju',                        label: 'Кайдзю',                         type: 'tag' },
  { value: 'Karuta',                       label: 'Каруда',                         type: 'tag' },
  { value: 'Kemonomimi',                   label: 'Кемономими',                     type: 'tag' },
  { value: 'Kids',                         label: 'Для детей',                      type: 'tag' },
  { value: 'Kingdom Management',           label: 'Управление королевством',        type: 'tag' },
  { value: 'Konbini',                      label: 'Конвини',                        type: 'tag' },
  { value: 'Kuudere',                      label: 'Кудэрэ',                         type: 'tag' },
  { value: 'Lacrosse',                     label: 'Лакросс',                        type: 'tag' },
  { value: 'Language Barrier',             label: 'Языковой барьер',                type: 'tag' },
  { value: 'LGBTQ+ Themes',               label: 'ЛГБТК+ тематика',               type: 'tag' },
  { value: 'Long Strip',                   label: 'Длинная полоса',                 type: 'tag' },
  { value: 'Lost Civilization',            label: 'Утраченная цивилизация',         type: 'tag' },
  { value: 'Love Triangle',                label: 'Любовный треугольник',           type: 'tag' },
  { value: 'Mafia',                        label: 'Мафия',                          type: 'tag' },
  { value: 'Magic',                        label: 'Магия',                          type: 'tag' },
  { value: 'Mahjong',                      label: 'Маджонг',                        type: 'tag' },
  { value: 'Maids',                        label: 'Горничные',                      type: 'tag' },
  { value: 'Makeup',                       label: 'Макияж',                         type: 'tag' },
  { value: 'Male Harem',                   label: 'Мужской гарем',                  type: 'tag' },
  { value: 'Male Protagonist',             label: 'Парень-протагонист',             type: 'tag' },
  { value: 'Manzai',                       label: 'Мандзай',                        type: 'tag' },
  { value: 'Marriage',                     label: 'Замужество',                     type: 'tag' },
  { value: 'Martial Arts',                 label: 'Боевые искусства',               type: 'tag' },
  { value: 'Matchmaking',                  label: 'Сватовство',                     type: 'tag' },
  { value: 'Matriarchy',                   label: 'Матриархат',                     type: 'tag' },
  { value: 'Medicine',                     label: 'Медицина',                       type: 'tag' },
  { value: 'Medieval',                     label: 'Средневековье',                  type: 'tag' },
  { value: 'Memory Manipulation',          label: 'Манипуляция памятью',            type: 'tag' },
  { value: 'Mermaid',                      label: 'Русалки',                        type: 'tag' },
  { value: 'Meta',                         label: 'Мета',                           type: 'tag' },
  { value: 'Metal Music',                  label: 'Метал',                          type: 'tag' },
  { value: 'Military',                     label: 'Военная тематика',               type: 'tag' },
  { value: 'Mixed Gender Harem',           label: 'Смешанный гарем',               type: 'tag' },
  { value: 'Mixed Media',                  label: 'Смешанные медиа',               type: 'tag' },
  { value: 'Modeling',                     label: 'Моделинг',                       type: 'tag' },
  { value: 'Monster Boy',                  label: 'Монстр-парень',                  type: 'tag' },
  { value: 'Monster Girl',                 label: 'Монстр-девушка',                 type: 'tag' },
  { value: 'Mopeds',                       label: 'Мопеды',                         type: 'tag' },
  { value: 'Motorcycles',                  label: 'Мотоциклы',                      type: 'tag' },
  { value: 'Mountaineering',               label: 'Альпинизм',                      type: 'tag' },
  { value: 'Musical Theater',              label: 'Мюзикл',                         type: 'tag' },
  { value: 'Mythology',                    label: 'Мифология',                      type: 'tag' },
  { value: 'Natural Disaster',             label: 'Природная катастрофа',           type: 'tag' },
  { value: 'Necromancy',                   label: 'Некромантия',                    type: 'tag' },
  { value: 'Nekomimi',                     label: 'Некомими',                       type: 'tag' },
  { value: 'Ninja',                        label: 'Ниндзя',                         type: 'tag' },
  { value: 'No Dialogue',                  label: 'Без диалогов',                   type: 'tag' },
  { value: 'Noir',                         label: 'Нуар',                           type: 'tag' },
  { value: 'Non-fiction',                  label: 'Нон-фикшн',                      type: 'tag' },
  { value: 'Nudity',                       label: 'Нагота',                         type: 'tag' },
  { value: 'Nun',                          label: 'Монахиня',                       type: 'tag' },
  { value: 'Office',                       label: 'Офис',                           type: 'tag' },
  { value: 'Office Lady',                  label: 'Офисная дама',                   type: 'tag' },
  { value: 'Oiran',                        label: 'Ойран',                          type: 'tag' },
  { value: 'Ojou-sama',                    label: 'Одзёсама',                       type: 'tag' },
  { value: 'Orphan',                       label: 'Сирота',                         type: 'tag' },
  { value: 'Otaku Culture',                label: 'Культура отаку',                 type: 'tag' },
  { value: 'Outdoor Activities',           label: 'Активный отдых',                 type: 'tag' },
  { value: 'Pandemic',                     label: 'Пандемия',                       type: 'tag' },
  { value: 'Parenthood',                   label: 'Родительство',                   type: 'tag' },
  { value: 'Parkour',                      label: 'Паркур',                         type: 'tag' },
  { value: 'Parody',                       label: 'Пародия',                        type: 'tag' },
  { value: 'Philosophy',                   label: 'Философия',                      type: 'tag' },
  { value: 'Photography',                  label: 'Фотография',                     type: 'tag' },
  { value: 'Pirates',                      label: 'Пираты',                         type: 'tag' },
  { value: 'Poker',                        label: 'Покер',                          type: 'tag' },
  { value: 'Police',                       label: 'Полиция',                        type: 'tag' },
  { value: 'Politics',                     label: 'Политика',                       type: 'tag' },
  { value: 'Polyamorous',                  label: 'Полиамория',                     type: 'tag' },
  { value: 'Post-Apocalyptic',             label: 'Постапокалипсис',                type: 'tag' },
  { value: 'POV',                          label: 'От первого лица',                type: 'tag' },
  { value: 'Pregnancy',                    label: 'Беременность',                   type: 'tag' },
  { value: 'Primarily Adult Cast',         label: 'Преим. взрослые',               type: 'tag' },
  { value: 'Primarily Animal Cast',        label: 'Преим. животные',               type: 'tag' },
  { value: 'Primarily Child Cast',         label: 'Преим. дети',                   type: 'tag' },
  { value: 'Primarily Female Cast',        label: 'Преим. женский каст',           type: 'tag' },
  { value: 'Primarily Male Cast',          label: 'Преим. мужской каст',           type: 'tag' },
  { value: 'Primarily Teen Cast',          label: 'Преим. подростки',              type: 'tag' },
  { value: 'Prison',                       label: 'Тюрьма',                         type: 'tag' },
  { value: 'Proxy Battle',                 label: 'Битва через посредников',        type: 'tag' },
  { value: 'Psychosexual',                 label: 'Психосексуальный',               type: 'tag' },
  { value: 'Puppetry',                     label: 'Кукольный театр',               type: 'tag' },
  { value: 'Rakugo',                       label: 'Ракуго',                         type: 'tag' },
  { value: 'Real Robot',                   label: 'Реальный робот',                 type: 'tag' },
  { value: 'Rehabilitation',               label: 'Реабилитация',                   type: 'tag' },
  { value: 'Reincarnation',                label: 'Реинкарнация',                   type: 'tag' },
  { value: 'Religion',                     label: 'Религия',                        type: 'tag' },
  { value: 'Rescue',                       label: 'Спасение',                       type: 'tag' },
  { value: 'Restaurant',                   label: 'Ресторан',                       type: 'tag' },
  { value: 'Revenge',                      label: 'Месть',                          type: 'tag' },
  { value: 'Reverse Isekai',               label: 'Обратный исекай',               type: 'tag' },
  { value: 'Robots',                       label: 'Роботы',                         type: 'tag' },
  { value: 'Rock Music',                   label: 'Рок',                            type: 'tag' },
  { value: 'Rotoscoping',                  label: 'Ротоскопинг',                    type: 'tag' },
  { value: 'Royal Affairs',                label: 'Дворцовые интриги',              type: 'tag' },
  { value: 'Rugby',                        label: 'Регби',                          type: 'tag' },
  { value: 'Rural',                        label: 'Сельская местность',             type: 'tag' },
  { value: 'Samurai',                      label: 'Самураи',                        type: 'tag' },
  { value: 'Satire',                       label: 'Сатира',                         type: 'tag' },
  { value: 'School',                       label: 'Школа',                          type: 'tag' },
  { value: 'School Club',                  label: 'Школьный клуб',                  type: 'tag' },
  { value: 'Scuba Diving',                 label: 'Подводное плавание',             type: 'tag' },
  { value: 'Seinen',                       label: 'Сэйнэн',                         type: 'tag' },
  { value: 'Shapeshifting',                label: 'Оборотничество',                 type: 'tag' },
  { value: 'Ships',                        label: 'Корабли',                        type: 'tag' },
  { value: 'Shogi',                        label: 'Сёги',                           type: 'tag' },
  { value: 'Shoujo',                       label: 'Сёдзё',                          type: 'tag' },
  { value: 'Shounen',                      label: 'Сёнэн',                          type: 'tag' },
  { value: 'Shrine Maiden',                label: 'Мико',                           type: 'tag' },
  { value: 'Skateboarding',                label: 'Скейтбординг',                   type: 'tag' },
  { value: 'Skeleton',                     label: 'Скелет',                         type: 'tag' },
  { value: 'Slapstick',                    label: 'Слэпстик',                       type: 'tag' },
  { value: 'Slavery',                      label: 'Рабство',                        type: 'tag' },
  { value: 'Snowscape',                    label: 'Снежный пейзаж',                 type: 'tag' },
  { value: 'Software Development',         label: 'Разработка ПО',                  type: 'tag' },
  { value: 'Space',                        label: 'Космос',                         type: 'tag' },
  { value: 'Space Opera',                  label: 'Космическая опера',              type: 'tag' },
  { value: 'Spearplay',                    label: 'Бой на копьях',                  type: 'tag' },
  { value: 'Steampunk',                    label: 'Стимпанк',                       type: 'tag' },
  { value: 'Stop Motion',                  label: 'Стоп-моушн',                     type: 'tag' },
  { value: 'Succubus',                     label: 'Суккуб',                         type: 'tag' },
  { value: 'Suicide',                      label: 'Суицид',                         type: 'tag' },
  { value: 'Sumo',                         label: 'Сумо',                           type: 'tag' },
  { value: 'Super Power',                  label: 'Суперспособности',               type: 'tag' },
  { value: 'Super Robot',                  label: 'Супер-робот',                    type: 'tag' },
  { value: 'Superhero',                    label: 'Супергерой',                     type: 'tag' },
  { value: 'Surfing',                      label: 'Сёрфинг',                        type: 'tag' },
  { value: 'Surreal Comedy',               label: 'Сюрреалистическая комедия',      type: 'tag' },
  { value: 'Survival',                     label: 'Выживание',                      type: 'tag' },
  { value: 'Swimming',                     label: 'Плавание',                       type: 'tag' },
  { value: 'Swordplay',                    label: 'Бой на мечах',                   type: 'tag' },
  { value: 'Table Tennis',                 label: 'Настольный теннис',              type: 'tag' },
  { value: 'Tanks',                        label: 'Танки',                          type: 'tag' },
  { value: 'Tanned Skin',                  label: 'Загорелая кожа',                 type: 'tag' },
  { value: 'Teacher',                      label: 'Учитель',                        type: 'tag' },
  { value: "Teens' Love",                  label: 'Подростковая любовь',            type: 'tag' },
  { value: 'Tennis',                       label: 'Теннис',                         type: 'tag' },
  { value: 'Terrorism',                    label: 'Терроризм',                      type: 'tag' },
  { value: 'Time Loop',                    label: 'Временная петля',                type: 'tag' },
  { value: 'Time Manipulation',            label: 'Манипуляция временем',           type: 'tag' },
  { value: 'Time Skip',                    label: 'Скачок во времени',              type: 'tag' },
  { value: 'Tokusatsu',                    label: 'Токусацу',                       type: 'tag' },
  { value: 'Tomboy',                       label: 'Томбой',                         type: 'tag' },
  { value: 'Torture',                      label: 'Пытки',                          type: 'tag' },
  { value: 'Tragedy',                      label: 'Трагедия',                       type: 'tag' },
  { value: 'Trains',                       label: 'Поезда',                         type: 'tag' },
  { value: 'Transgender',                  label: 'Трансгендер',                    type: 'tag' },
  { value: 'Travel',                       label: 'Путешествия',                    type: 'tag' },
  { value: 'Triads',                       label: 'Триады',                         type: 'tag' },
  { value: 'Tsundere',                     label: 'Цундэрэ',                        type: 'tag' },
  { value: 'Twins',                        label: 'Близнецы',                       type: 'tag' },
  { value: 'Unrequited Love',              label: 'Безответная любовь',             type: 'tag' },
  { value: 'Urban',                        label: 'Городская среда',                type: 'tag' },
  { value: 'Urban Fantasy',                label: 'Городское фэнтези',              type: 'tag' },
  { value: 'Vampire',                      label: 'Вампиры',                        type: 'tag' },
  { value: 'Vertical Video',               label: 'Вертикальное видео',             type: 'tag' },
  { value: 'Veterinarian',                 label: 'Ветеринар',                      type: 'tag' },
  { value: 'Video Games',                  label: 'Видеоигры',                      type: 'tag' },
  { value: 'Vikings',                      label: 'Викинги',                        type: 'tag' },
  { value: 'Villainess',                   label: 'Злодейка',                       type: 'tag' },
  { value: 'Virtual World',                label: 'Виртуальный мир',               type: 'tag' },
  { value: 'Vocal Synth',                  label: 'Вокальный синтезатор',           type: 'tag' },
  { value: 'Volleyball',                   label: 'Волейбол',                       type: 'tag' },
  { value: 'VTuber',                       label: 'ВТубер',                         type: 'tag' },
  { value: 'War',                          label: 'Война',                          type: 'tag' },
  { value: 'Werewolf',                     label: 'Оборотень',                      type: 'tag' },
  { value: 'Wilderness',                   label: 'Дикая природа',                  type: 'tag' },
  { value: 'Witch',                        label: 'Ведьма',                         type: 'tag' },
  { value: 'Work',                         label: 'Работа',                         type: 'tag' },
  { value: 'Wrestling',                    label: 'Борьба',                         type: 'tag' },
  { value: 'Writing',                      label: 'Писательство',                   type: 'tag' },
  { value: 'Wuxia',                        label: 'Уся',                            type: 'tag' },
  { value: 'Yakuza',                       label: 'Якудза',                         type: 'tag' },
  { value: 'Yandere',                      label: 'Яндэрэ',                         type: 'tag' },
  { value: 'Youkai',                       label: 'Ёкай',                           type: 'tag' },
  { value: 'Yuri',                         label: 'Юри',                            type: 'tag' },
  { value: 'Zombie',                       label: 'Зомби',                          type: 'tag' },
];

// Маппинг сортировок: URL-param → AniList MediaSort
export const SORT_OPTIONS = [
  { value: 'score_desc', label: 'Рейтинг ↓', anilist: 'SCORE_DESC' },
  { value: 'score_asc',  label: 'Рейтинг ↑', anilist: 'SCORE' },
  { value: 'date_desc',  label: 'Новее',      anilist: 'START_DATE_DESC' },
  { value: 'date_asc',   label: 'Старее',     anilist: 'START_DATE' },
] as const;

export type SortValue = (typeof SORT_OPTIONS)[number]['value'];

export function sortToAniList(sort: string | null): string {
  return SORT_OPTIONS.find((o) => o.value === sort)?.anilist ?? 'TRENDING_DESC';
}
