name: Deploy

on:
  push:
    branches:
      - main   # или master — смотри как называется твоя ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/animeview
            git pull origin main
            npm install --production
            npm run build
            pm2 restart animeview
